//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bier()
        {
            this.item = new HashSet<item>();
        }
    
        public int Id { get; set; }
        public int InhoudId { get; set; }
        public string Naam { get; set; }
        public string Label { get; set; }
        public string Temperatuur { get; set; }
        public string Barcode { get; set; }
    
        public virtual inhoud inhoud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item> item { get; set; }
    }
}
