//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class inhoud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inhoud()
        {
            this.bier = new HashSet<bier>();
        }
    
        public int Id { get; set; }
        public Nullable<double> Inhoud1 { get; set; }
        public string Eenheid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bier> bier { get; set; }
    }
}
