//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int id { get; set; }
        public int Bierid { get; set; }
        public int LocatieColumn { get; set; }
        public string AspNetUsersId { get; set; }
        public int Aantal { get; set; }
        public bool Openbaar { get; set; }
    
        public virtual aspnetusers aspnetusers { get; set; }
        public virtual bier bier { get; set; }
        public virtual locatie locatie { get; set; }
    }
}
