//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class locatie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public locatie()
        {
            this.item = new HashSet<item>();
        }
    
        public int Id { get; set; }
        public string Naam { get; set; }
        public double Temperatuur { get; set; }
        public string AspNetUsersId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item> item { get; set; }
        public virtual aspnetusers aspnetusers { get; set; }
    }
}
